version: '2'
services:
    web:
        build: .
        ports:
            - '9000:9000'
        container_name: devops-node-app
        environment:
        - 'MYSQL=mysql://user:pass@example.com:3306/dbname'